# Generated by Django 3.0 on 2020-05-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id_distrik', models.AutoField(primary_key=True, serialize=False)),
                ('nama_distrik', models.CharField(max_length=50)),
                ('kadis', models.CharField(max_length=100)),
                ('sekdis', models.CharField(max_length=100)),
                ('kotak_kadis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kampung',
            fields=[
                ('id_kampung', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kampung', models.CharField(max_length=100)),
                ('kakam', models.CharField(max_length=100)),
                ('sekam', models.CharField(max_length=100)),
                ('kontak_kakam', models.CharField(max_length=20)),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.Distrik')),
            ],
        ),
    ]
