# Generated by Django 3.0 on 2020-06-07 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0002_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='deskripsi',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Aduan',
            fields=[
                ('id_aduan', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('nama_pengadu', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('no_telfon', models.CharField(max_length=13)),
                ('deskripsi', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='upload_doc/% Y/% m/% d/')),
                ('date', models.DateTimeField()),
                ('kode_unik', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.Distrik')),
                ('kampung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.Kampung')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.Kategori')),
            ],
        ),
    ]
