# Generated by Django 3.0 on 2020-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0004_auto_20200607_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduan',
            name='file',
            field=models.FileField(upload_to='upload_doc/'),
        ),
    ]
