# Generated by Django 3.0 on 2020-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0005_auto_20200607_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
