# Generated by Django 3.0 on 2020-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0008_auto_20200615_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petunjuk',
            fields=[
                ('id_pen', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=500)),
                ('sample', models.CharField(max_length=150)),
            ],
        ),
    ]
