# Generated by Django 3.0 on 2020-06-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pengaduan', '0009_petunjuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useraduan', to=settings.AUTH_USER_MODEL),
        ),
    ]
